"""Add telephone field to users

Revision ID: 05d6a98dc1c6
Revises: 59b2b3227eb5
Create Date: 2026-04-30 21:13:00.678386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05d6a98dc1c6'
down_revision: Union[str, Sequence[str], None] = '59b2b3227eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telephone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telephone')
    # ### end Alembic commands ###
